### PR TITLE
Updates the documentation with respect to dependencies

### PR DESCRIPTION
**Pull request by thunterdb**

### CODE REVIEW

**Comment by brkyvz** [comment]
@thunterdb Could you please add the same to `README.md` as well? Thanks!

**Comment by JoshRosen** [comment]
Why not specify this as a dependency in your `setup.py` package description?

**Comment by brkyvz** [comment]
@JoshRosen It is. I believe this doesn't work very well with people who have Anaconda installed

**Comment by thunterdb** [comment]
Because I am learning the syntax of setup.py right now... Will fix.

**Comment by JoshRosen** [comment]
You should try using https://pypi.python.org/pypi/pyroma to perform validation sanity checks on your `setup.py` file.

**Comment by thunterdb** [comment]
Pyroma says it is some Comté, as before. Do you know why it is failing the test?

**Pull request closed without merging**
